# Generated by Django 2.0.2 on 2018-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='step',
            name='in_detail',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
