# Generated by Django 2.0.2 on 2018-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='accounts/profilepics/'),
        ),
    ]
