# Generated by Django 2.0.2 on 2018-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='accounts/profilepics/default_avatar.png', upload_to='accounts/profilepics/'),
        ),
    ]
