# Generated by Django 2.0.2 on 2018-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoverreports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverreport',
            name='file',
            field=models.FileField(upload_to='handovereports/'),
        ),
    ]
